name: Test and Build

on:
  push:
    branches:    
      - master
      - main
      - "release?/**"
    tags:        
      - v[0-9]+.[0-9]+.[0-9]+*
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-version-analysis: 14.x
    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [10.x, 12.x, 13.x, 14.x]

    steps:
      - name: Shallow Checkout
        uses: actions/checkout@v2
        if: ${{ matrix.node-version != env.node-version-analysis }}

      - name: Full Checkout
        uses: actions/checkout@v2
        # Do full check out when SonarCloud action is performed later on
        if: ${{ matrix.node-version == env.node-version-analysis }}
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        env:
          CI: true

      - name: Test the project
        run: npm run test

      - name: Run SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        if: ${{ matrix.node-version == env.node-version-analysis }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish Code Coverage
        uses: codecov/codecov-action@v1
        if: ${{ matrix.node-version == env.node-version-analysis }}
        with:
          files: ./coverage/clover.xml
          flags: tests
          name: codecov-umbrella
          fail_ci_if_error: true
